// Generated by CoffeeScript 1.8.0
(function() {
  var async, express, request, router;

  express = require('express');

  async = require('async');

  request = require('request');

  router = express.Router();


  /* GET home page. */

  router.get('/', function(req, res, next) {
    res.render('index', {
      title: 'Express'
    });
  });

  router.get('/auth', function(req, res) {
    var codeUrl, form, key, op, redirect_uri;
    key = process.env.pocket1;
    codeUrl = 'https://getpocket.com/v3/oauth/request';
    redirect_uri = process.env.pocket_url;
    form = {
      'consumer_key': key,
      'redirect_uri': redirect_uri
    };
    op = {
      url: codeUrl,
      form: form
    };
    return async.auto({
      getCode: function(cb) {
        return request.post(op, function(err, response, body) {
          var code;
          if (err) {
            return saveErr(op.url, 1, {
              err: err
            });
          }
          console.log("body1 ==>", body);
          if (response.statusCode === 200) {
            code = body.split('=')[1];
            return cb(null, code);
          } else {
            req.session.error = "连接Pocket出错";
            return res.redirect('/');
          }
        });
      },
      directUrl: [
        'getCode', function(cb, result) {
          var code, url;
          code = result.getCode;
          req.session.code = code;
          url = "https://getpocket.com/auth/authorize?request_token=" + code + "&redirect_uri=" + redirect_uri;
          return res.redirect(url);
        }
      ]
    });
  });

  router.get('/oauth_callback', function(req, res) {
    var form, key, op, token, url, username;
    url = 'https://getpocket.com/v3/oauth/authorize';
    key = process.env.pocket1;
    username = '';
    token = '';
    form = {
      consumer_key: key,
      code: req.session.code,
      headers: {
        'Content-Type': 'application/json; charset=UTF-8'
      }
    };
    op = {
      url: url,
      form: form
    };
    return request.post(op, function(err, response, body) {
      var infoArr;
      if (err) {
        return saveErr(op.url, 1, {
          err: err
        });
      }
      if (response.statusCode === 200) {
        console.log("body =>", body);
        infoArr = body.split('&');
        token = infoArr[0].split('=')[1];
        username = infoArr[1].split('=')[1];
        return res.send("okok");
      } else {
        req.session.error = "获取pocket token 出错";
        console.log(token);
        return res.redirect('/');
      }
    });
  });

  router.get('/test', function(req, res) {
    var form, op, url;
    url = 'https://getpocket.com/v3/get';
    form = {
      consumer_key: process.env.pocket1,
      access_token: '',
      count: '2',
      detailType: 'complete'
    };
    op = {
      url: url,
      form: form
    };
    return request.post(op, function(err, response, body) {
      if (err) {
        return console.log(err);
      }
      return console.log(body);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
